### PR TITLE
Friendship v2

### PR DESCRIPTION
**Pull request by dibdas**
implement friendships with 2 rows for mutual friendship.

### CODE REVIEW

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello there, great job and effort you've put into this project, you've set up the mutual friends functionality correctly. However, there are still a few more changes to make in order to get this PR approved. Please keep up the great work! 👍😊

<hr>

- [x] In order to get all posts written by users on their friends, students can use the simple method in the User model (in order to NOT do it with Enumerable). Please consider this issue in your timeline_posts private methods in the posts controller.

```
# User model

def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
end
```

- [x] Kindly add more integration and unit tests for the friendship model.

<hr>

Kindly do the above requirements and ask for another CRR.
Good luck and happy coding. 👨‍💻💻

<hr>

Please if you'd like to ask any question about my comments, feel free to contact on Slack with the name "Mahmoud Bakr". I'd be happy to help.

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work. 💻 👀 ✨ 
- Great job applying some of the changes requested previously.
## However, there are some changes required 👀 🧰 🔨 🔧 
- The point of adding two rows per friendship is to avoid having to construct the list of friends with a double query as you do here:
image
- Please refer to these articles to get a better idea of what's expected here:
https://explainextended.com/2009/03/07/selecting-friends/
https://stackoverflow.com/questions/4219979/sql-best-practice-for-a-friendship-table
- Basically what you have to do is take the queries from the articles and translate them to Active Record queries. Remember: you must avoid using more than a single query to pull a user's complete list of friends. Otherwise there is no real efficiency improvement in using double friendshp rows.

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Review by voscarmv — CHANGES_REQUESTED** [review]
Hi,

There don't seem to be any changes in this Pull Request. Perhaps you submitted the wrong Pull Request link to the Code Review Request form?

If you're simply having trouble understanding the assignment, you may take a look at this example from my own Friendships V2 project:

https://github.com/voscarmv/ror-social-scaffold/pull/3/commits/06896ca182ff2d4905d152f712a20bc30c325c65

Notice how, with two friendship rows, we only have to query once for the whole friends list:

image

Here's the example of my User controller. Please try to implement something like this in your project: https://github.com/voscarmv/ror-social-scaffold/blob/06896ca182ff2d4905d152f712a20bc30c325c65/app/models/user.rb

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hi @dibdas & @udberg**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
