### PR TITLE
Friendship v1

### PR DESCRIPTION
**Pull request by dibdas**
In this branch, we have continued building our project which now has the following features;

As a guest user:

I want to be able to create an account/log in.

I can see only the “Sign in” and “Sign out” pages.

As a logged-in user:

I want to be able to see all users' lists.

I want to be able to see the selected user page with their user name and all posts written by them (the most recent posts on the top).

I want to be able to send a friendship invitation.

I want to see a button “Invite to friendship” next to the name of the user who is not my friend yet - on both users’ list and the single-user page.

I want to be able to see pending friendship invitations sent to me from other users.

I want to be able to accept or reject friendships' invitations.

I want to be able to create new posts (text only).

I want to be able to like/dislike posts (but I can like a single post only once).

I want to be able to add comments to posts.

I want to be able to see the “Timeline” page with posts (with the number of likes and comments) written by me and all my friends (the most recent posts on the top).

The timeline page should be the root page of the app.

### CODE REVIEW

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Udberg John & Dibyendu Das** 
Good job with your first submission for this project :muscle:  :muscle:
Nice job implementing the friendship model :clap: :clap: :clap:  
There are just some details to improve before you can go ahead:

- [x] Improve your README file, provide details of what is it about, what technologies did you use, how to set up the project.
- [x] The rspec tests are not working:



- [x] Add both unit and integration tests
- [x] In your tests, use at most one "expect" for each "it"
- [x] After login, the root page should only show the comment of the current user and its friends
- [x] "accept request" and "decline request" are not working

 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:full_moon:
**Hi team!
Great job on this milestone so far:clap::clap:**.

**Major highlights**

- The milestone has a descriptive readme
- The codebase is clean

However, we still need to make a few changes to get the milestone approved.

**To improve**

- [x] User model `has_many :inverted_friendships, class_name: "Friendship", foreign_key: "friend_id"` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Kindly ensure this reflects in the user model.

- [x] User can invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). This is currently not possible. I normally get a noMethod error. Kindly fix the bug. see [screen-shot](https://imgur.com/a/SxpAW1N) for reference.

- [x] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Ensure we add this feature

- [x] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Also ensure we add this feature.

- [x] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)).

- [x] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)).

- [x] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)). Currently, it includes all users and not their friends. Kindly fix this.

- [x] All the tests are currently failing when I run bundle exec rspec. See [screen-shot](https://imgur.com/a/Icxjdo2) for reference. Kindly fix this.

Make the above-required changes and when you are ready, request another review.
Kindly drop your questions :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan

**Review by oloomoses — CHANGES_REQUESTED** [review]
# Changes Required
**Hello team, you have done well on implementing some of the changes from the previous review :muscle:
However, there are some mandatory changes that you are yet to implement. :point_down:** 

- [x] User can invite friends. This is currently not possible. You only have an invite button that is not functional

- [x] User can see friendship requests. Ensure we add this feature

- [x] User has to accept friendship request to start friendship. Also ensure we add this feature.

- [x] User can reject a friendship request.

- [x] Posts timeline includes posts written by logged-in user and their friends (screenshot from Pathwright). Currently, it includes all users and not their friends. Kindly fix this.

Kindly implement the above changes before submitting another code review.
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
## HAPPY CODING 
_Slack: Oloo Moses_

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hi guys**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
