### PR TITLE
Data archi doc

### PR DESCRIPTION
**Pull request by dibdas**
In this milestone, we designed an ERD that shows the attributes and relationships among users, friendship, posts, likes, and comments.

### CODE REVIEW

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello there, great job setting up your mind about the relationships between the models you'll be working on and making such a detailed and organized diagram. However, there are still some issues that need to be fixed in this milestone to get approved 😊🙏

- [x] Please write a more descriptive PR summary i.e. "In this milestone, I managed to design an ERD that shows ..."
- [x] Post table is missing the Primary Key (PK) which refers to a single post_id. Please fix that in your ERD to P.K instead of Key.
- [x] Post table should have user_id column as Foreign Key (FK) instead of Key. Kindly modify that too.

<hr>

And that'd be an advance congrats on completing this milestone after making the changes.
Good luck with the next and happy coding 👨‍💻💻

<hr>

You can always reach me on Slack with the name "Mahmoud Bakr" :)

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

Hello, @dibdas and @udberg, Great job! 👏  Your ERD looks good
Let's make a few changes, and we will be done.

- [x] **Kindly make sure that linter checks are running on your PR**
- [x] Your commit messages should be capitalized, and written in the imperative tense. You can watch this [video](https://www.loom.com/share/00771f369b7b47fc968c019ecf0d3ba6) on how to edit your commit messages using git rebase
 See [Git Commit Best Practices](https://github.com/trein/dev-best-practices/wiki/Git-Commit-Best-Practices#formatting-rules) for more insights

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes required :recycle: :
Hey  👋🏾 👋🏾 you have tried to implement a good ERD, however, let's make it even better.

REQUIRED:
- [x] Since `sender_id` and `receiver_id` are both instances of the `user` model, there should be an `inverse relationship` between the user and the friendship model. This implies that a user can send many friend requests and can also receive many friend requests, but a friend request, either sent or received, can belong to just only one user. See the diagram below for details:



That's all :smile: kindly submit another review when done.
Regards
Rindra Josia

**Review by whiz25 — APPROVED** [review]
## Approved ✅ 
Nice work on making the requested changes. The ERD diagram now looks better. 
Merge and proceed to the next project.

### Martin Afani

**Pull request merged**
